### ISSUE TITLE
Video reproduce in native fullscreen of iOS 9

### ISSUE THREAD

**Issue by danieltigse** [hawksley/eleVR-Web-Player#36] opened 2016-03-26 19:11 UTC
There is a way to stop the fullscreen mode of iPhone when I reproduce the video?

![simulator screen shot mar 26 2016 2 09 44 pm](https://cloud.githubusercontent.com/assets/1870723/14061963/8c079ffe-f35c-11e5-873e-d99b5f765714.png)

Beside that, the fullscreen button doesn't work on iOS

**Comment by hawksley** [comment] 2016-03-27 15:53
This is the same issue as an earlier one with iOS8. This is an issue that we can't get around with Safari as of the last check, although there are a few things you can do to ameliorate it a bit, discussed in the earlier bug.

**Comment by hawksley** [comment] 2016-03-27 15:54
Duplicate of https://github.com/hawksley/eleVR-Web-Player/issues/9

**Closed as completed** 2016-03-27 15:54 UTC
Labels: duplicate

**Comment by yoanntel** [comment] 2016-04-10 07:11
Hi,

I have same issue..... play pause and every controls not working  IOS 9.3.1with safari.
when i clicked on play button the video launched on native Safari player without 360. 
I tried also fullscreen ... same issue the video back on elevr player but paused. I can't play it

**Comment by yoanntel** [comment] 2016-04-10 08:38
I found http://krpano.com/video/ who play video inline and it's working ....... I don't know how to apply that hack on elevr player like : http://stackoverflow.com/questions/30855662/inline-html5-video-on-iphone
if someone can help me ........
